[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "/intent/pay/checkStatus/"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus"
  status = 200
  force = true
  
[[redirects]]
  from = "/intent/pay/checkStatus/payment-method-manifest.json"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus/payment-method-manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/intent/pay/checkStatus/payment-apay.json"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus/payment-apay.json"
  status = 200
  force = true
